### PR TITLE
fix fprintf Wformat-security and int-vs-long Wformat compiler warnings

### PR DESCRIPTION
**Pull request by nabbi**
Corrects  format-security compiler warnings with fprintf statements by declaring the %s formatting.
` warning: format not a string literal and no format arguments [-Wformat-security]`

Encountered with hardened gcc 9.2.0 Gentoo Linux

### CODE REVIEW

**Comment by nabbi** [comment]
Also corrects int vs long compiler format warnings
`warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘time_t’ {aka ‘long int’}`
`warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int’ [-Wformat=]`

**Comment by AmyBSOD** [comment]
Thanks for making this, and you coincidentally made it while I'm too busy with real life stuff to be doing any real development anyway so I can probably merge this... one day ;) can't predict when that will be, but it'll probably be merged before I do any other development. This is very helpful :)

**Comment by AmyBSOD** [comment]
Got my office PC's internet working again sooner than expected, so I merged it already :)

**Comment by moon-chilled** [comment]
Does the proxy winport actually still work? ;o

**Pull request merged**
